[versions]
activityComposeVersion = "1.8.2"
agp = "8.5.1"
alphacepheiVoskAndroid = "0.3.47"
composeBomVersion = "2025.03.00"
jnaPlatform = "5.13.0"
jnaVersion = "5.13.0"
kotlin = "1.9.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.04.01"
lifecycleRuntimeKtxVersion = "2.7.0"
navigationCompose = "2.7.7"
voskAndroid = "0.3.45"
voskAndroidService = "0.3.45"
voskAndroidVersion = "0.3.45"
voskVoskAndroid = "0.3.45"

[libraries]
androidx-activity-compose-v182 = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-compose-bom-v20240201 = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx-v270 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jnaPlatform" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
material3 = { module = "androidx.compose.material3:material3" }
net-jna = { module = "net.java.dev.jna:jna", version.ref = "jnaVersion" }
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
vosk-android = { module = "com.alphacephei:vosk-android", version.ref = "voskAndroid" }
vosk-android-service = { module = "com.alphacephei:vosk-android-service", version.ref = "voskAndroidService" }
vosk-android-v0332 = { module = "com.alphacephei:vosk-android", version.ref = "voskAndroidVersion" }
vosk-android-v0347 = { module = "com.alphacephei:vosk-android", version.ref = "alphacepheiVoskAndroid" }
vosk-vosk-android = { module = "org.vosk:vosk-android", version.ref = "voskVoskAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

